#!/usr/bin/env python3

import sys
import argparse
from colorsh import Colorsh, Color, Style

def parse_args():
    ap = argparse.ArgumentParser(description="colorsh-cli")
    ap.add_argument('infile', nargs='?', type=argparse.FileType('r'), default=sys.stdin)
    ap.add_argument("-e", "--encoding", choices=["ansi", "tmux"], default="ansi")
    ap.add_argument("-f", "--fg", help="foreground color")
    ap.add_argument("-b", "--bg", help="background color")
    ap.add_argument("-s", "--style", nargs="+", help="comma separated formatting", default=[])

    return ap.parse_args()

def main():
    args = parse_args()

    encoding = args.encoding
    fg = Color(args.fg)
    bg = Color(args.bg)

    style = Style(args.style)

    msg = ""
    for line in args.infile:
        msg += line

    print(Colorsh.decorate(msg.strip(), args.encoding, fg, bg, style))

if __name__ == "__main__":
    main()
